apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rots-tsl
  annotations:
    agentj.com/production-branch: main
spec:
  owner: rots-regie-op-techniek-en-storingen
  type: website
  lifecycle: experimental
